# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Base.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

import main,sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setFixedSize(800,600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStatusTip("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.TAB_Home = QtWidgets.QWidget()
        self.TAB_Home.setStatusTip("")
        self.TAB_Home.setObjectName("TAB_Home")
        self.LB_Home_Welcome = QtWidgets.QLabel(self.TAB_Home)
        self.LB_Home_Welcome.setGeometry(QtCore.QRect(10, 0, 331, 16))
        self.LB_Home_Welcome.setObjectName("LB_Home_Welcome")
        self.LB_Home_BuildBy = QtWidgets.QLabel(self.TAB_Home)
        self.LB_Home_BuildBy.setGeometry(QtCore.QRect(0, 530, 331, 16))
        self.LB_Home_BuildBy.setObjectName("LB_Home_BuildBy")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.TAB_Home)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(-30, 30, 781, 354))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TB_Home_Item_Tue_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Tue_2.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Tue_2.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Tue_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Tue_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Tue_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Tue_2.setObjectName("TB_Home_Item_Tue_2")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Tue_2, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setMaximumSize(QtCore.QSize(17, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_9.sizePolicy().hasHeightForWidth())
        self.comboBox_9.setSizePolicy(sizePolicy)
        self.comboBox_9.setMaximumSize(QtCore.QSize(201, 16777215))
        self.comboBox_9.setObjectName("comboBox_9")
        self.gridLayout_2.addWidget(self.comboBox_9, 8, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setMaximumSize(QtCore.QSize(17, 16777215))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 10, 0, 1, 1)
        self.TB_Home_Item_Mon_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Mon_6.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Mon_6.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Mon_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Mon_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Mon_6.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Mon_6.setObjectName("TB_Home_Item_Mon_6")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Mon_6, 6, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setMaximumSize(QtCore.QSize(17, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 9, 0, 1, 1)
        self.TB_Home_Item_Fri_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Fri_9.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Fri_9.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Fri_9.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Fri_9.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Fri_9.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Fri_9.setObjectName("TB_Home_Item_Fri_9")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Fri_9, 9, 6, 1, 1)
        self.TB_Home_Item_Fri_10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Fri_10.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Fri_10.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Fri_10.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Fri_10.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Fri_10.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Fri_10.setObjectName("TB_Home_Item_Fri_10")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Fri_10, 10, 6, 1, 1)
        self.TB_Home_Item_Fri_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Fri_1.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Fri_1.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Fri_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Fri_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Fri_1.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Fri_1.setObjectName("TB_Home_Item_Fri_1")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Fri_1, 1, 6, 1, 1)
        self.TB_Home_Item_Tue_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Tue_7.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Tue_7.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Tue_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Tue_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Tue_7.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Tue_7.setObjectName("TB_Home_Item_Tue_7")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Tue_7, 7, 3, 1, 1)
        self.TB_Home_Item_Wed_10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Wed_10.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Wed_10.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Wed_10.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Wed_10.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Wed_10.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Wed_10.setObjectName("TB_Home_Item_Wed_10")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Wed_10, 10, 4, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.comboBox_5.setMaximumSize(QtCore.QSize(201, 16777215))
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_2.addWidget(self.comboBox_5, 5, 1, 1, 1)
        self.TB_Home_Item_Thu_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Thu_6.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Thu_6.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Thu_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Thu_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Thu_6.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Thu_6.setObjectName("TB_Home_Item_Thu_6")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Thu_6, 6, 5, 1, 1)
        self.TB_Home_Item_Mon_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Mon_7.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Mon_7.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Mon_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Mon_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Mon_7.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Mon_7.setObjectName("TB_Home_Item_Mon_7")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Mon_7, 7, 2, 1, 1)
        self.TB_Home_Item_Fri_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Fri_4.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Fri_4.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Fri_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Fri_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Fri_4.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Fri_4.setObjectName("TB_Home_Item_Fri_4")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Fri_4, 4, 6, 1, 1)
        self.TB_Home_Item_Fri_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Fri_7.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Fri_7.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Fri_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Fri_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Fri_7.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Fri_7.setObjectName("TB_Home_Item_Fri_7")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Fri_7, 7, 6, 1, 1)
        self.TB_Home_Item_Wed_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Wed_5.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Wed_5.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Wed_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Wed_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Wed_5.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Wed_5.setObjectName("TB_Home_Item_Wed_5")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Wed_5, 5, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 5, 1, 1)
        self.TB_Home_Item_Mon_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.TB_Home_Item_Mon_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Mon_1.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Mon_1.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Mon_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Mon_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Mon_1.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Mon_1.setObjectName("TB_Home_Item_Mon_1")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Mon_1, 1, 2, 1, 1)
        self.TB_Home_Item_Tue_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Tue_5.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Tue_5.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Tue_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Tue_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Tue_5.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Tue_5.setObjectName("TB_Home_Item_Tue_5")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Tue_5, 5, 3, 1, 1)
        self.TB_Home_Item_Fri_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Fri_5.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Fri_5.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Fri_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Fri_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Fri_5.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Fri_5.setObjectName("TB_Home_Item_Fri_5")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Fri_5, 5, 6, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setMaximumSize(QtCore.QSize(17, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.TB_Home_Item_Wed_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Wed_2.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Wed_2.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Wed_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Wed_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Wed_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Wed_2.setObjectName("TB_Home_Item_Wed_2")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Wed_2, 2, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setMaximumSize(QtCore.QSize(17, 16777215))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 6, 0, 1, 1)
        self.TB_Home_Item_Thu_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Thu_9.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Thu_9.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Thu_9.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Thu_9.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Thu_9.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Thu_9.setObjectName("TB_Home_Item_Thu_9")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Thu_9, 9, 5, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMaximumSize(QtCore.QSize(201, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 1, 1, 1, 1)
        self.TB_Home_Item_Mon_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Mon_4.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Mon_4.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Mon_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Mon_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Mon_4.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Mon_4.setObjectName("TB_Home_Item_Mon_4")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Mon_4, 4, 2, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_8.sizePolicy().hasHeightForWidth())
        self.comboBox_8.setSizePolicy(sizePolicy)
        self.comboBox_8.setMaximumSize(QtCore.QSize(201, 16777215))
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_2.addWidget(self.comboBox_8, 10, 1, 1, 1)
        self.TB_Home_Item_Thu_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Thu_3.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Thu_3.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Thu_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Thu_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Thu_3.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Thu_3.setObjectName("TB_Home_Item_Thu_3")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Thu_3, 3, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 6, 1, 1)
        self.TB_Home_Item_Wed_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Wed_1.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Wed_1.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Wed_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Wed_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Wed_1.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Wed_1.setObjectName("TB_Home_Item_Wed_1")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Wed_1, 1, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setMaximumSize(QtCore.QSize(17, 16777215))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 7, 0, 1, 1)
        self.TB_Home_Item_Tue_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Tue_1.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Tue_1.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Tue_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Tue_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Tue_1.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Tue_1.setObjectName("TB_Home_Item_Tue_1")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Tue_1, 1, 3, 1, 1)
        self.TB_Home_Item_Thu_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Thu_7.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Thu_7.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Thu_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Thu_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Thu_7.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Thu_7.setObjectName("TB_Home_Item_Thu_7")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Thu_7, 7, 5, 1, 1)
        self.label1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.gridLayout_2.addWidget(self.label1, 0, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMaximumSize(QtCore.QSize(201, 16777215))
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_2.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.TB_Home_Item_Thu_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Thu_5.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Thu_5.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Thu_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Thu_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Thu_5.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Thu_5.setObjectName("TB_Home_Item_Thu_5")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Thu_5, 5, 5, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setMaximumSize(QtCore.QSize(201, 16777215))
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_2.addWidget(self.comboBox_4, 4, 1, 1, 1)
        self.TB_Home_Item_Tue_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Tue_9.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Tue_9.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Tue_9.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Tue_9.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Tue_9.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Tue_9.setObjectName("TB_Home_Item_Tue_9")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Tue_9, 9, 3, 1, 1)
        self.TB_Home_Item_Mon_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Mon_5.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Mon_5.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Mon_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Mon_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Mon_5.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Mon_5.setObjectName("TB_Home_Item_Mon_5")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Mon_5, 5, 2, 1, 1)
        self.TB_Home_Item_Thu_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Thu_2.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Thu_2.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Thu_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Thu_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Thu_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Thu_2.setObjectName("TB_Home_Item_Thu_2")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Thu_2, 2, 5, 1, 1)
        self.TB_Home_Item_Mon_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Mon_2.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Mon_2.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Mon_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Mon_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Mon_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Mon_2.setObjectName("TB_Home_Item_Mon_2")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Mon_2, 2, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setMaximumSize(QtCore.QSize(17, 16777215))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 8, 0, 1, 1)
        self.TB_Home_Item_Mon_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Mon_9.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Mon_9.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Mon_9.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Mon_9.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Mon_9.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Mon_9.setObjectName("TB_Home_Item_Mon_9")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Mon_9, 9, 2, 1, 1)
        self.TB_Home_Item_Fri_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Fri_6.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Fri_6.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Fri_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Fri_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Fri_6.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Fri_6.setObjectName("TB_Home_Item_Fri_6")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Fri_6, 6, 6, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setMaximumSize(QtCore.QSize(201, 16777215))
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_2.addWidget(self.comboBox_3, 3, 1, 1, 1)
        self.TB_Home_Item_Wed_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Wed_3.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Wed_3.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Wed_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Wed_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Wed_3.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Wed_3.setObjectName("TB_Home_Item_Wed_3")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Wed_3, 3, 4, 1, 1)
        self.TB_Home_Item_Wed_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Wed_7.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Wed_7.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Wed_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Wed_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Wed_7.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Wed_7.setObjectName("TB_Home_Item_Wed_7")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Wed_7, 7, 4, 1, 1)
        self.TB_Home_Item_Mon_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Mon_8.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Mon_8.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Mon_8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Mon_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Mon_8.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Mon_8.setObjectName("TB_Home_Item_Mon_8")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Mon_8, 8, 2, 1, 1)
        self.TB_Home_Item_Wed_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Wed_8.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Wed_8.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Wed_8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Wed_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Wed_8.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Wed_8.setObjectName("TB_Home_Item_Wed_8")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Wed_8, 8, 4, 1, 1)
        self.TB_Home_Item_Thu_10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Thu_10.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Thu_10.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Thu_10.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Thu_10.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Thu_10.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Thu_10.setObjectName("TB_Home_Item_Thu_10")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Thu_10, 10, 5, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_7.sizePolicy().hasHeightForWidth())
        self.comboBox_7.setSizePolicy(sizePolicy)
        self.comboBox_7.setMaximumSize(QtCore.QSize(201, 16777215))
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout_2.addWidget(self.comboBox_7, 9, 1, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_10.sizePolicy().hasHeightForWidth())
        self.comboBox_10.setSizePolicy(sizePolicy)
        self.comboBox_10.setMaximumSize(QtCore.QSize(201, 16777215))
        self.comboBox_10.setObjectName("comboBox_10")
        self.gridLayout_2.addWidget(self.comboBox_10, 6, 1, 1, 1)
        self.TB_Home_Item_Fri_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Fri_8.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Fri_8.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Fri_8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Fri_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Fri_8.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Fri_8.setObjectName("TB_Home_Item_Fri_8")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Fri_8, 8, 6, 1, 1)
        self.TB_Home_Item_Thu_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Thu_4.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Thu_4.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Thu_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Thu_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Thu_4.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Thu_4.setObjectName("TB_Home_Item_Thu_4")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Thu_4, 4, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setMaximumSize(QtCore.QSize(17, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.TB_Home_Item_Wed_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Wed_6.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Wed_6.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Wed_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Wed_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Wed_6.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Wed_6.setObjectName("TB_Home_Item_Wed_6")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Wed_6, 6, 4, 1, 1)
        self.TB_Home_Item_Tue_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Tue_6.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Tue_6.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Tue_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Tue_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Tue_6.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Tue_6.setObjectName("TB_Home_Item_Tue_6")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Tue_6, 6, 3, 1, 1)
        self.TB_Home_Item_Wed_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Wed_9.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Wed_9.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Wed_9.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Wed_9.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Wed_9.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Wed_9.setObjectName("TB_Home_Item_Wed_9")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Wed_9, 9, 4, 1, 1)
        self.TB_Home_Item_Mon_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Mon_3.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Mon_3.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Mon_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Mon_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Mon_3.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Mon_3.setObjectName("TB_Home_Item_Mon_3")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Mon_3, 3, 2, 1, 1)
        self.TB_Home_Item_Fri_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Fri_3.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Fri_3.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Fri_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Fri_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Fri_3.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Fri_3.setObjectName("TB_Home_Item_Fri_3")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Fri_3, 3, 6, 1, 1)
        self.TB_Home_Item_Thu_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Thu_1.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Thu_1.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Thu_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Thu_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Thu_1.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Thu_1.setObjectName("TB_Home_Item_Thu_1")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Thu_1, 1, 5, 1, 1)
        self.TB_Home_Item_Wed_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Wed_4.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Wed_4.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Wed_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Wed_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Wed_4.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Wed_4.setObjectName("TB_Home_Item_Wed_4")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Wed_4, 4, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setMaximumSize(QtCore.QSize(201, 16777215))
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_2.addWidget(self.comboBox_6, 7, 1, 1, 1)
        self.TB_Home_Item_Tue_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Tue_3.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Tue_3.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Tue_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Tue_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Tue_3.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Tue_3.setObjectName("TB_Home_Item_Tue_3")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Tue_3, 3, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setMaximumSize(QtCore.QSize(17, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 1)
        self.TB_Home_Item_Tue_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Tue_8.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Tue_8.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Tue_8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Tue_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Tue_8.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Tue_8.setObjectName("TB_Home_Item_Tue_8")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Tue_8, 8, 3, 1, 1)
        self.TB_Home_Item_Fri_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Fri_2.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Fri_2.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Fri_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Fri_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Fri_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Fri_2.setObjectName("TB_Home_Item_Fri_2")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Fri_2, 2, 6, 1, 1)
        self.TB_Home_Item_Thu_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Thu_8.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Thu_8.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Thu_8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Thu_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Thu_8.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Thu_8.setObjectName("TB_Home_Item_Thu_8")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Thu_8, 8, 5, 1, 1)
        self.TB_Home_Item_Mon_10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Mon_10.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Mon_10.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Mon_10.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Mon_10.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Mon_10.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Mon_10.setObjectName("TB_Home_Item_Mon_10")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Mon_10, 10, 2, 1, 1)
        self.TB_Home_Item_Tue_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Tue_4.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Tue_4.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Tue_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Tue_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Tue_4.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Tue_4.setObjectName("TB_Home_Item_Tue_4")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Tue_4, 4, 3, 1, 1)
        self.TB_Home_Item_Tue_10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(36)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Home_Item_Tue_10.sizePolicy().hasHeightForWidth())
        self.TB_Home_Item_Tue_10.setSizePolicy(sizePolicy)
        self.TB_Home_Item_Tue_10.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TB_Home_Item_Tue_10.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TB_Home_Item_Tue_10.setAlignment(QtCore.Qt.AlignCenter)
        self.TB_Home_Item_Tue_10.setObjectName("TB_Home_Item_Tue_10")
        self.gridLayout_2.addWidget(self.TB_Home_Item_Tue_10, 10, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setMaximumSize(QtCore.QSize(17, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.BTN_Home_RUN = QtWidgets.QPushButton(self.TAB_Home)
        self.BTN_Home_RUN.setGeometry(QtCore.QRect(590, 460, 171, 71))
        self.BTN_Home_RUN.clicked.connect(self.FTN_Start)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.BTN_Home_RUN.setFont(font)
        self.BTN_Home_RUN.setObjectName("BTN_Home_RUN")
        self.tabWidget.addTab(self.TAB_Home, "")
        self.TAB_User = QtWidgets.QWidget()
        self.TAB_User.setStatusTip("")
        self.TAB_User.setObjectName("TAB_User")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.TAB_User)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 231, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HL_user_top = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HL_user_top.setContentsMargins(0, 0, 0, 0)
        self.HL_user_top.setObjectName("HL_user_top")
        self.LB_User_name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LB_User_name.sizePolicy().hasHeightForWidth())
        self.LB_User_name.setSizePolicy(sizePolicy)
        self.LB_User_name.setObjectName("LB_User_name")
        self.HL_user_top.addWidget(self.LB_User_name)
        self.LE_User_name = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_User_name.sizePolicy().hasHeightForWidth())
        self.LE_User_name.setSizePolicy(sizePolicy)
        self.LE_User_name.setInputMask("")
        self.LE_User_name.setMaxLength(50)
        self.LE_User_name.setObjectName("LE_User_name")
        self.HL_user_top.addWidget(self.LE_User_name)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.TAB_User)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(310, 10, 311, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.HL_user_top_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.HL_user_top_2.setContentsMargins(0, 0, 0, 0)
        self.HL_user_top_2.setObjectName("HL_user_top_2")
        self.LB_User_heritage = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LB_User_heritage.sizePolicy().hasHeightForWidth())
        self.LB_User_heritage.setSizePolicy(sizePolicy)
        self.LB_User_heritage.setObjectName("LB_User_heritage")
        self.HL_user_top_2.addWidget(self.LB_User_heritage)
        self.CB_User_heritage = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.CB_User_heritage.setProperty("WorleyParsons", "")
        self.CB_User_heritage.setObjectName("CB_User_heritage")
        self.CB_User_heritage.addItem("")
        self.CB_User_heritage.addItem("")
        self.HL_user_top_2.addWidget(self.CB_User_heritage)
        self.TBL_User_WBS = QtWidgets.QTableWidget(self.TAB_User)
        self.TBL_User_WBS.setGeometry(QtCore.QRect(0, 130, 771, 281))
        self.TBL_User_WBS.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TBL_User_WBS.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TBL_User_WBS.setObjectName("TBL_User_WBS")
        self.TBL_User_WBS.setColumnCount(5)
        self.TBL_User_WBS.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_User_WBS.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_User_WBS.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_User_WBS.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_User_WBS.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_User_WBS.setHorizontalHeaderItem(4, item)
        self.BTN_User_Save = QtWidgets.QPushButton(self.TAB_User)
        self.BTN_User_Save.setGeometry(QtCore.QRect(700, 520, 93, 28))
        self.BTN_User_Save.setObjectName("BTN_User_Save")
        #self.BTN_User_Save.clicked.connect()
        self.LB_User_BuildBy = QtWidgets.QLabel(self.TAB_User)
        self.LB_User_BuildBy.setGeometry(QtCore.QRect(0, 530, 331, 16))
        self.LB_User_BuildBy.setObjectName("LB_User_BuildBy")
        self.tabWidget.addTab(self.TAB_User, "")
        self.TAB_Credentials = QtWidgets.QWidget()
        self.TAB_Credentials.setObjectName("TAB_Credentials")
        self.gridLayoutWidget = QtWidgets.QWidget(self.TAB_Credentials)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 761, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LB_Credentials_User1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LB_Credentials_User1.setObjectName("LB_Credentials_User1")
        self.horizontalLayout.addWidget(self.LB_Credentials_User1)
        spacerItem = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.LE_Credentials_User1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_Credentials_User1.sizePolicy().hasHeightForWidth())
        self.LE_Credentials_User1.setSizePolicy(sizePolicy)
        self.LE_Credentials_User1.setInputMask("")
        self.LE_Credentials_User1.setText("")
        self.LE_Credentials_User1.setMaxLength(100)
        self.LE_Credentials_User1.setObjectName("LE_Credentials_User1")
        self.horizontalLayout.addWidget(self.LE_Credentials_User1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LB_Credentials_Pass2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LB_Credentials_Pass2.setObjectName("LB_Credentials_Pass2")
        self.horizontalLayout_3.addWidget(self.LB_Credentials_Pass2)
        self.LE_Credentials_Pass2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.LE_Credentials_Pass2.setInputMask("")
        self.LE_Credentials_Pass2.setMaxLength(100)
        self.LE_Credentials_Pass2.setObjectName("LE_Credentials_Pass2")
        self.LE_Credentials_Pass2.setDisabled(True)
        self.horizontalLayout_3.addWidget(self.LE_Credentials_Pass2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LB_Credentials_Pass1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LB_Credentials_Pass1.setObjectName("LB_Credentials_Pass1")
        self.horizontalLayout_2.addWidget(self.LB_Credentials_Pass1)
        spacerItem1 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.LE_Credentials_Pass1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.LE_Credentials_Pass1.setInputMask("")
        self.LE_Credentials_Pass1.setMaxLength(100)
        self.LE_Credentials_Pass1.setObjectName("LE_Credentials_Pass1")
        self.horizontalLayout_2.addWidget(self.LE_Credentials_Pass1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LB_Credentials_User2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LB_Credentials_User2.setObjectName("LB_Credentials_User2")
        self.horizontalLayout_4.addWidget(self.LB_Credentials_User2)
        self.LE_Credentials_User2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.LE_Credentials_User2.setInputMask("")
        self.LE_Credentials_User2.setMaxLength(100)
        self.LE_Credentials_User2.setObjectName("LE_Credentials_User2")
        self.LE_Credentials_User2.setDisabled(True)
        self.horizontalLayout_4.addWidget(self.LE_Credentials_User2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CkB_Credentials_Dual_log = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.CkB_Credentials_Dual_log.setObjectName("CkB_Credentials_Dual_log")
        self.CkB_Credentials_Dual_log.stateChanged.connect(self.Ftn_Credentials_Dual_state)
        self.horizontalLayout_5.addWidget(self.CkB_Credentials_Dual_log)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.formLayoutWidget = QtWidgets.QWidget(self.TAB_Credentials)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 190, 481, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.Form_Credentials_Saved = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.Form_Credentials_Saved.setContentsMargins(0, 0, 0, 0)
        self.Form_Credentials_Saved.setObjectName("Form_Credentials_Saved")
        self.LB_Credentials_User1_Text = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_User1_Text.setObjectName("LB_Credentials_User1_Text")
        self.Form_Credentials_Saved.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LB_Credentials_User1_Text)
        self.LB_Credentials_User1_Saved = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_User1_Saved.setObjectName("LB_Credentials_User1_Saved")
        self.Form_Credentials_Saved.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LB_Credentials_User1_Saved)
        self.LB_Credentials_Pass1_Text = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_Pass1_Text.setObjectName("LB_Credentials_Pass1_Text")
        self.Form_Credentials_Saved.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.LB_Credentials_Pass1_Text)
        self.LB_Credentials_Pass1_Saved = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_Pass1_Saved.setObjectName("LB_Credentials_Pass1_Saved")
        self.Form_Credentials_Saved.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LB_Credentials_Pass1_Saved)
        self.LB_Credentials_User2_Text = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_User2_Text.setObjectName("LB_Credentials_User2_Text")
        self.Form_Credentials_Saved.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LB_Credentials_User2_Text)
        self.LB_Credentials_User2_Saved = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_User2_Saved.setObjectName("LB_Credentials_User2_Saved")
        self.Form_Credentials_Saved.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LB_Credentials_User2_Saved)
        self.LB_Credentials_Pass2_Text = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_Pass2_Text.setObjectName("LB_Credentials_Pass2_Text")
        self.Form_Credentials_Saved.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.LB_Credentials_Pass2_Text)
        self.LB_Credentials_Pass2_Saved = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_Pass2_Saved.setObjectName("LB_Credentials_Pass2_Saved")
        self.Form_Credentials_Saved.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LB_Credentials_Pass2_Saved)
        self.LB_Credentials_Header1 = QtWidgets.QLabel(self.TAB_Credentials)
        self.LB_Credentials_Header1.setGeometry(QtCore.QRect(10, 170, 121, 16))
        self.LB_Credentials_Header1.setObjectName("LB_Credentials_Header1")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.TAB_Credentials)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(530, 510, 261, 51))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.BTN_Credentials_Clear = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.BTN_Credentials_Clear.setObjectName("BTN_Credentials_Clear")
        self.BTN_Credentials_Clear.clicked.connect(self.FTN_Credential_Delete)
        self.horizontalLayout_6.addWidget(self.BTN_Credentials_Clear)
        self.BTN_Credentials_Save = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.BTN_Credentials_Save.setObjectName("BTN_Credentials_Save")
        self.BTN_Credentials_Save.clicked.connect(self.FTN_BTN_Credentials_Save)
        self.horizontalLayout_6.addWidget(self.BTN_Credentials_Save)

        self.LB_Credentials_BuildBy = QtWidgets.QLabel(self.TAB_Credentials)
        self.LB_Credentials_BuildBy.setGeometry(QtCore.QRect(0, 530, 331, 16))
        self.LB_Credentials_BuildBy.setObjectName("LB_Credentials_BuildBy")
        self.tabWidget.addTab(self.TAB_Credentials, "")
        self.TAB_Feedback = QtWidgets.QWidget()
        self.TAB_Feedback.setObjectName("TAB_Feedback")
        self.LB_Feedback_header = QtWidgets.QLabel(self.TAB_Feedback)
        self.LB_Feedback_header.setGeometry(QtCore.QRect(140, 120, 501, 281))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LB_Feedback_header.setFont(font)
        self.LB_Feedback_header.setWordWrap(True)
        self.LB_Feedback_header.setObjectName("LB_Feedback_header")
        self.tabWidget.addTab(self.TAB_Feedback, "")
        self.TAB_Readme = QtWidgets.QWidget()
        self.TAB_Readme.setObjectName("TAB_Readme")
        self.frame = QtWidgets.QFrame(self.TAB_Readme)
        self.frame.setGeometry(QtCore.QRect(10, 0, 781, 541))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 663, 381))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LB_Feed_1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.LB_Feed_1.setFont(font)
        self.LB_Feed_1.setObjectName("LB_Feed_1")
        self.verticalLayout_2.addWidget(self.LB_Feed_1)
        self.LB_Feed_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LB_Feed_2.setObjectName("LB_Feed_2")
        self.verticalLayout_2.addWidget(self.LB_Feed_2)
        self.LB_Feed_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LB_Feed_3.setObjectName("LB_Feed_3")
        self.verticalLayout_2.addWidget(self.LB_Feed_3)
        self.LB_Feed_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LB_Feed_4.setObjectName("LB_Feed_4")
        self.verticalLayout_2.addWidget(self.LB_Feed_4)
        self.LB_Feed_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LB_Feed_5.setObjectName("LB_Feed_5")
        self.verticalLayout_2.addWidget(self.LB_Feed_5)
        self.LB_Feed_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.LB_Feed_6.setFont(font)
        self.LB_Feed_6.setObjectName("LB_Feed_6")
        self.verticalLayout_2.addWidget(self.LB_Feed_6)
        self.LB_Feed_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LB_Feed_7.setObjectName("LB_Feed_7")
        self.verticalLayout_2.addWidget(self.LB_Feed_7)
        self.LB_Feed_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LB_Feed_8.setObjectName("LB_Feed_8")
        self.verticalLayout_2.addWidget(self.LB_Feed_8)
        self.LB_Feed_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LB_Feed_9.setObjectName("LB_Feed_9")
        self.verticalLayout_2.addWidget(self.LB_Feed_9)
        self.tabWidget.addTab(self.TAB_Readme, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LB_Home_Welcome.setText(_translate("MainWindow", "Hi ______"))
        self.LB_Home_BuildBy.setText(_translate("MainWindow", "Build by Connor Clark: Graduate Process Engineer"))
        self.label_8.setText(_translate("MainWindow", "3"))
        self.label_15.setText(_translate("MainWindow", "10"))
        self.label_14.setText(_translate("MainWindow", "9"))
        self.label_5.setText(_translate("MainWindow", "Thursday"))
        self.label_7.setText(_translate("MainWindow", "2"))
        self.label_11.setText(_translate("MainWindow", "6"))
        self.label_4.setText(_translate("MainWindow", "Wednesday"))
        self.label_6.setText(_translate("MainWindow", "Friday"))
        self.label_12.setText(_translate("MainWindow", "7"))
        self.label1.setText(_translate("MainWindow", "Project"))
        self.label_13.setText(_translate("MainWindow", "8"))
        self.label_9.setText(_translate("MainWindow", "4"))
        self.label_2.setText(_translate("MainWindow", "Monday"))
        self.label_10.setText(_translate("MainWindow", "5"))
        self.label_3.setText(_translate("MainWindow", "Tuesday"))
        self.label.setText(_translate("MainWindow", "1"))
        self.BTN_Home_RUN.setText(_translate("MainWindow", "START"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_Home), _translate("MainWindow", "Home"))
        self.LB_User_name.setText(_translate("MainWindow", "Name:"))
        self.LE_User_name.setText(_translate("MainWindow", "Enter your first name"))
        self.LB_User_heritage.setText(_translate("MainWindow", "Heritage Timesheet Application"))
        self.CB_User_heritage.setCurrentText(_translate("MainWindow", "WorleyParsons"))
        self.CB_User_heritage.setItemText(0, _translate("MainWindow", "WorleyParsons"))
        self.CB_User_heritage.setItemText(1, _translate("MainWindow", "Jacobs ECR"))
        self.TBL_User_WBS.setToolTip(_translate("MainWindow", "<html><head/><body><p>List of all saved projects codes</p></body></html>"))
        item = self.TBL_User_WBS.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Index"))
        item = self.TBL_User_WBS.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Common Name"))
        item = self.TBL_User_WBS.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Project/ WBS"))
        item = self.TBL_User_WBS.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Task"))
        item = self.TBL_User_WBS.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Type"))
        self.BTN_User_Save.setText(_translate("MainWindow", "Save"))
        self.LB_User_BuildBy.setText(_translate("MainWindow", "Build by Connor Clark: Graduate Process Engineer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_User), _translate("MainWindow", "User Preferences"))
        self.LB_Credentials_User1.setText(_translate("MainWindow", "Worley Email:"))
        self.LE_Credentials_User1.setStatusTip(_translate("MainWindow", "Your work email address e.g connor.clark@worleyparsons.com"))
        self.LB_Credentials_Pass2.setText(_translate("MainWindow", "Timesheet Password:"))
        self.LE_Credentials_Pass2.setStatusTip(_translate("MainWindow", "Password required to log into timesheet"))
        self.LB_Credentials_Pass1.setText(_translate("MainWindow", "Worley Password:"))
        self.LE_Credentials_Pass1.setStatusTip(_translate("MainWindow", "The password you use with your Worley email"))
        self.LB_Credentials_User2.setText(_translate("MainWindow", "Timesheet Username:"))
        self.LE_Credentials_User2.setStatusTip(_translate("MainWindow", "Username required for timesheet e.g XXXXXX"))
        self.CkB_Credentials_Dual_log.setStatusTip(_translate("MainWindow", "Only check if different credentials are required to connect to your timesheet"))
        self.CkB_Credentials_Dual_log.setText(_translate("MainWindow", "Log on required for timesheet"))
        self.LB_Credentials_User1_Text.setText(_translate("MainWindow", "Email:"))
        self.LB_Credentials_User1_Saved.setText(_translate("MainWindow", "No saved data"))
        self.LB_Credentials_Pass1_Text.setText(_translate("MainWindow", "Password:"))
        self.LB_Credentials_Pass1_Saved.setText(_translate("MainWindow", "No saved data"))
        self.LB_Credentials_User2_Text.setText(_translate("MainWindow", "User:"))
        self.LB_Credentials_User2_Saved.setText(_translate("MainWindow", "No saved data"))
        self.LB_Credentials_Pass2_Text.setText(_translate("MainWindow", "Password:"))
        self.LB_Credentials_Pass2_Saved.setText(_translate("MainWindow", "No saved data"))
        self.LB_Credentials_Header1.setText(_translate("MainWindow", "Current Saved Data:"))
        self.BTN_Credentials_Clear.setStatusTip(_translate("MainWindow", "Deletes ALL saved usernames and passwords."))
        self.BTN_Credentials_Clear.setText(_translate("MainWindow", "Clear All Saved Data"))
        self.BTN_Credentials_Save.setStatusTip(_translate("MainWindow", "Update stored credentials"))
        self.BTN_Credentials_Save.setText(_translate("MainWindow", "Overwrite / Save"))
        self.LB_Credentials_BuildBy.setText(_translate("MainWindow", "Build by Connor Clark: Graduate Process Engineer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_Credentials), _translate("MainWindow", "User Credentials"))
        self.LB_Feedback_header.setText(_translate("MainWindow", "Hi _____, thank you for using my program! This page isnt working yet, so if you have any bugs, suggestion, improvments or just want to say hello, please feel free to email me at: connor.clark@worleyparsons.com"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_Feedback), _translate("MainWindow", "Feedback"))
        self.LB_Feed_1.setText(_translate("MainWindow", "Things you should know."))
        self.LB_Feed_2.setText(_translate("MainWindow", "All data is stored locally is stored locally on your machine."))
        self.LB_Feed_3.setText(_translate("MainWindow", "Feel free to share this around with people who are internal to Worley only."))
        self.LB_Feed_4.setText(_translate("MainWindow", "Share the latest version with the link:   [sharepoint.link]"))
        self.LB_Feed_5.setText(_translate("MainWindow", "If you do share your copy make sure you run the delete all personal data! "))
        self.LB_Feed_6.setText(_translate("MainWindow", "How to use:"))
        self.LB_Feed_7.setText(_translate("MainWindow", "Each time this runs you are required to authenticate the login using your mobile, as per Worley Policy"))
        self.LB_Feed_8.setText(_translate("MainWindow", "Currently new project codes must be added via the csv file in the main folder."))
        self.LB_Feed_9.setText(_translate("MainWindow", "XXXX"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_Readme), _translate("MainWindow", "README"))

        self.startupload()

    #def tab_home_functions(self):
        #

    #tab_user_preferences_functions(self):
    def startupload(self):
        user1, pass1, user2, pass2 = main.startupload()
        if user1 is None:
            pass
        else:
            self.FTN_Credential_refresh(user1, pass1, user2, pass2)



    def Ftn_Credentials_Dual_state(self):
        if self.CkB_Credentials_Dual_log.isChecked():
            self.LE_Credentials_User2.setDisabled(False)
            self.LE_Credentials_Pass2.setDisabled(False)
        else:
            self.LE_Credentials_User2.setText("")
            self.LE_Credentials_Pass2.setText("")
            self.LE_Credentials_User2.setDisabled(True)
            self.LE_Credentials_Pass2.setDisabled(True)
        pass

    def FTN_BTN_Credentials_Save(self):
        #todo Add Confirmation pop up,
        if self.LE_Credentials_User1.text() != "" or self.LE_Credentials_Pass1.text() != "":
            success = main.user_credentials_overwrite(self.LE_Credentials_User1.text(),self.LE_Credentials_Pass1.text(),self.LE_Credentials_User2.text(),self.LE_Credentials_Pass2.text())
        else:
            success = False

        if success:
            #pass1 = len(self.LE_Credentials_Pass1.text()) * '*'
            self.FTN_Credential_refresh(self.LE_Credentials_User1.text(),len(self.LE_Credentials_Pass1.text()) * '*',self.LE_Credentials_User2.text(),len(self.LE_Credentials_Pass2.text()) * '*')
        else:
            print("Missing User or Password")
            pass

    def FTN_Credential_refresh(self,user1,pass1,user2,pass2):
        if user2 == str(''):
            user2 = 'No saved data'
        if pass2 == str(''):
            pass2 = 'No saved data'
        self.LE_Credentials_User1.setText("")
        self.LE_Credentials_Pass1.setText("")
        self.LE_Credentials_User2.setText("")
        self.LE_Credentials_Pass2.setText("")
        self.LB_Credentials_User1_Saved.setText(user1)
        self.LB_Credentials_Pass1_Saved.setText(pass1)
        self.LB_Credentials_User2_Saved.setText(user2)
        self.LB_Credentials_Pass2_Saved.setText(pass2)

    def FTN_Credential_Delete(self):
        main.Encryption().clear()
        user1, pass1, user2, pass2 = 'No saved data','No saved data','No saved data','No saved data'
        self.FTN_Credential_refresh(user1, pass1, user2, pass2)

    def FTN_Start(self):

        main.launch(self.CB_User_heritage.currentText())
        self.close_application()

    def close_application(self):
        sys.exit()

    #def tab_user_credentials_functions(self):
        #pass

    #def tab_feedback_functions(self):
        #pass


