# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Base.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStatusTip("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.TAB_Home = QtWidgets.QWidget()
        self.TAB_Home.setStatusTip("")
        self.TAB_Home.setObjectName("TAB_Home")
        self.LB_Home_Welcome = QtWidgets.QLabel(self.TAB_Home)
        self.LB_Home_Welcome.setGeometry(QtCore.QRect(10, 10, 331, 16))
        self.LB_Home_Welcome.setObjectName("LB_Home_Welcome")
        self.tabWidget.addTab(self.TAB_Home, "")
        self.TAB_User = QtWidgets.QWidget()
        self.TAB_User.setStatusTip("")
        self.TAB_User.setObjectName("TAB_User")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.TAB_User)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 231, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HL_user_top = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HL_user_top.setContentsMargins(0, 0, 0, 0)
        self.HL_user_top.setObjectName("HL_user_top")
        self.LB_User_name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LB_User_name.sizePolicy().hasHeightForWidth())
        self.LB_User_name.setSizePolicy(sizePolicy)
        self.LB_User_name.setObjectName("LB_User_name")
        self.HL_user_top.addWidget(self.LB_User_name)
        self.LE_User_name = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_User_name.sizePolicy().hasHeightForWidth())
        self.LE_User_name.setSizePolicy(sizePolicy)
        self.LE_User_name.setInputMask("")
        self.LE_User_name.setMaxLength(50)
        self.LE_User_name.setObjectName("LE_User_name")
        self.HL_user_top.addWidget(self.LE_User_name)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.TAB_User)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(310, 10, 311, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.HL_user_top_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.HL_user_top_2.setContentsMargins(0, 0, 0, 0)
        self.HL_user_top_2.setObjectName("HL_user_top_2")
        self.LB_User_heritage = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LB_User_heritage.sizePolicy().hasHeightForWidth())
        self.LB_User_heritage.setSizePolicy(sizePolicy)
        self.LB_User_heritage.setObjectName("LB_User_heritage")
        self.HL_user_top_2.addWidget(self.LB_User_heritage)
        self.CB_User_heritage = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.CB_User_heritage.setProperty("WorleyParsons", "")
        self.CB_User_heritage.setObjectName("CB_User_heritage")
        self.CB_User_heritage.addItem("")
        self.CB_User_heritage.addItem("")
        self.HL_user_top_2.addWidget(self.CB_User_heritage)
        self.TBL_User_WBS = QtWidgets.QTableWidget(self.TAB_User)
        self.TBL_User_WBS.setGeometry(QtCore.QRect(0, 130, 771, 301))
        self.TBL_User_WBS.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TBL_User_WBS.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TBL_User_WBS.setObjectName("TBL_User_WBS")
        self.TBL_User_WBS.setColumnCount(5)
        self.TBL_User_WBS.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_User_WBS.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_User_WBS.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_User_WBS.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_User_WBS.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_User_WBS.setHorizontalHeaderItem(4, item)
        self.BTN_User_Save = QtWidgets.QPushButton(self.TAB_User)
        self.BTN_User_Save.setGeometry(QtCore.QRect(690, 490, 93, 28))
        self.BTN_User_Save.setObjectName("BTN_User_Save")
        self.tabWidget.addTab(self.TAB_User, "")
        self.TAB_Credentials = QtWidgets.QWidget()
        self.TAB_Credentials.setObjectName("TAB_Credentials")
        self.gridLayoutWidget = QtWidgets.QWidget(self.TAB_Credentials)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 761, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LB_Credentials_User1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LB_Credentials_User1.setObjectName("LB_Credentials_User1")
        self.horizontalLayout.addWidget(self.LB_Credentials_User1)
        spacerItem = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.LE_Credentials_User1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_Credentials_User1.sizePolicy().hasHeightForWidth())
        self.LE_Credentials_User1.setSizePolicy(sizePolicy)
        self.LE_Credentials_User1.setInputMask("")
        self.LE_Credentials_User1.setText("")
        self.LE_Credentials_User1.setMaxLength(100)
        self.LE_Credentials_User1.setObjectName("LE_Credentials_User1")
        self.horizontalLayout.addWidget(self.LE_Credentials_User1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LB_Credentials_Pass2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LB_Credentials_Pass2.setObjectName("LB_Credentials_Pass2")
        self.horizontalLayout_3.addWidget(self.LB_Credentials_Pass2)
        self.LE_Credentials_Pass2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.LE_Credentials_Pass2.setInputMask("")
        self.LE_Credentials_Pass2.setMaxLength(100)
        self.LE_Credentials_Pass2.setObjectName("LE_Credentials_Pass2")
        self.horizontalLayout_3.addWidget(self.LE_Credentials_Pass2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LB_Credentials_Pass1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LB_Credentials_Pass1.setObjectName("LB_Credentials_Pass1")
        self.horizontalLayout_2.addWidget(self.LB_Credentials_Pass1)
        spacerItem1 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.LE_Credentials_Pass1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.LE_Credentials_Pass1.setInputMask("")
        self.LE_Credentials_Pass1.setMaxLength(100)
        self.LE_Credentials_Pass1.setObjectName("LE_Credentials_Pass1")
        self.horizontalLayout_2.addWidget(self.LE_Credentials_Pass1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LB_Credentials_User2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LB_Credentials_User2.setObjectName("LB_Credentials_User2")
        self.horizontalLayout_4.addWidget(self.LB_Credentials_User2)
        self.LE_Credentials_User2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.LE_Credentials_User2.setInputMask("")
        self.LE_Credentials_User2.setMaxLength(100)
        self.LE_Credentials_User2.setObjectName("LE_Credentials_User2")
        self.horizontalLayout_4.addWidget(self.LE_Credentials_User2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CkB_Credentials_Dual_log = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.CkB_Credentials_Dual_log.setObjectName("CkB_Credentials_Dual_log")
        self.horizontalLayout_5.addWidget(self.CkB_Credentials_Dual_log)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.formLayoutWidget = QtWidgets.QWidget(self.TAB_Credentials)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 190, 481, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.Form_Credentials_Saved = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.Form_Credentials_Saved.setContentsMargins(0, 0, 0, 0)
        self.Form_Credentials_Saved.setObjectName("Form_Credentials_Saved")
        self.LB_Credentials_User1_Text = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_User1_Text.setObjectName("LB_Credentials_User1_Text")
        self.Form_Credentials_Saved.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LB_Credentials_User1_Text)
        self.LB_Credentials_User1_Saved = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_User1_Saved.setObjectName("LB_Credentials_User1_Saved")
        self.Form_Credentials_Saved.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LB_Credentials_User1_Saved)
        self.LB_Credentials_Pass1_Text = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_Pass1_Text.setObjectName("LB_Credentials_Pass1_Text")
        self.Form_Credentials_Saved.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.LB_Credentials_Pass1_Text)
        self.LB_Credentials_Pass1_Saved = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_Pass1_Saved.setObjectName("LB_Credentials_Pass1_Saved")
        self.Form_Credentials_Saved.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LB_Credentials_Pass1_Saved)
        self.LB_Credentials_User2_Text = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_User2_Text.setObjectName("LB_Credentials_User2_Text")
        self.Form_Credentials_Saved.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LB_Credentials_User2_Text)
        self.LB_Credentials_User2_Saved = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_User2_Saved.setObjectName("LB_Credentials_User2_Saved")
        self.Form_Credentials_Saved.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LB_Credentials_User2_Saved)
        self.LB_Credentials_Pass2_Text = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_Pass2_Text.setObjectName("LB_Credentials_Pass2_Text")
        self.Form_Credentials_Saved.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.LB_Credentials_Pass2_Text)
        self.LB_Credentials_Pass2_Saved = QtWidgets.QLabel(self.formLayoutWidget)
        self.LB_Credentials_Pass2_Saved.setObjectName("LB_Credentials_Pass2_Saved")
        self.Form_Credentials_Saved.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LB_Credentials_Pass2_Saved)
        self.LB_Credentials_Header1 = QtWidgets.QLabel(self.TAB_Credentials)
        self.LB_Credentials_Header1.setGeometry(QtCore.QRect(10, 170, 121, 16))
        self.LB_Credentials_Header1.setObjectName("LB_Credentials_Header1")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.TAB_Credentials)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(524, 489, 261, 51))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.BTN_Credentials_Clear = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.BTN_Credentials_Clear.setObjectName("BTN_Credentials_Clear")
        self.horizontalLayout_6.addWidget(self.BTN_Credentials_Clear)
        self.BTN_Credentials_Save = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.BTN_Credentials_Save.setObjectName("BTN_Credentials_Save")
        self.horizontalLayout_6.addWidget(self.BTN_Credentials_Save)
        self.tabWidget.addTab(self.TAB_Credentials, "")
        self.TAB_Feedback = QtWidgets.QWidget()
        self.TAB_Feedback.setObjectName("TAB_Feedback")
        self.LB_Feedback_header = QtWidgets.QLabel(self.TAB_Feedback)
        self.LB_Feedback_header.setGeometry(QtCore.QRect(140, 130, 501, 271))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.LB_Feedback_header.setFont(font)
        self.LB_Feedback_header.setObjectName("LB_Feedback_header")
        self.tabWidget.addTab(self.TAB_Feedback, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LB_Home_Welcome.setText(_translate("MainWindow", "Hi [Name]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_Home), _translate("MainWindow", "Home"))
        self.LB_User_name.setText(_translate("MainWindow", "Name:"))
        self.LE_User_name.setText(_translate("MainWindow", "Enter your first name"))
        self.LB_User_heritage.setText(_translate("MainWindow", "Heritage Timesheet Application"))
        self.CB_User_heritage.setCurrentText(_translate("MainWindow", "WorleyParsons"))
        self.CB_User_heritage.setItemText(0, _translate("MainWindow", "WorleyParsons"))
        self.CB_User_heritage.setItemText(1, _translate("MainWindow", "Jacobs ECR"))
        self.TBL_User_WBS.setToolTip(_translate("MainWindow", "<html><head/><body><p>List of all saved projects codes</p></body></html>"))
        item = self.TBL_User_WBS.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Index"))
        item = self.TBL_User_WBS.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Common Name"))
        item = self.TBL_User_WBS.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Project/ WBS"))
        item = self.TBL_User_WBS.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Task"))
        item = self.TBL_User_WBS.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Type"))
        self.BTN_User_Save.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_User), _translate("MainWindow", "User Preferences"))
        self.LB_Credentials_User1.setText(_translate("MainWindow", "Worley Email:"))
        self.LE_Credentials_User1.setStatusTip(_translate("MainWindow", "Your work email address e.g connor.clark@worleyparsons.com"))
        self.LB_Credentials_Pass2.setText(_translate("MainWindow", "Timesheet Password:"))
        self.LE_Credentials_Pass2.setStatusTip(_translate("MainWindow", "Password required to log into timesheet"))
        self.LB_Credentials_Pass1.setText(_translate("MainWindow", "Worley Password:"))
        self.LE_Credentials_Pass1.setStatusTip(_translate("MainWindow", "The password you use with your Worley email"))
        self.LB_Credentials_User2.setText(_translate("MainWindow", "Timesheet Username:"))
        self.LE_Credentials_User2.setStatusTip(_translate("MainWindow", "Username required for timesheet e.g XXXXXX"))
        self.CkB_Credentials_Dual_log.setStatusTip(_translate("MainWindow", "Only check if different credentials are required to connect to your timesheet"))
        self.CkB_Credentials_Dual_log.setText(_translate("MainWindow", "Log on required for timesheet"))
        self.LB_Credentials_User1_Text.setText(_translate("MainWindow", "Email:"))
        self.LB_Credentials_User1_Saved.setText(_translate("MainWindow", "No saved data"))
        self.LB_Credentials_Pass1_Text.setText(_translate("MainWindow", "Password:"))
        self.LB_Credentials_Pass1_Saved.setText(_translate("MainWindow", "No saved data"))
        self.LB_Credentials_User2_Text.setText(_translate("MainWindow", "User:"))
        self.LB_Credentials_User2_Saved.setText(_translate("MainWindow", "No saved data"))
        self.LB_Credentials_Pass2_Text.setText(_translate("MainWindow", "Password:"))
        self.LB_Credentials_Pass2_Saved.setText(_translate("MainWindow", "No saved data"))
        self.LB_Credentials_Header1.setText(_translate("MainWindow", "Current Saved Data:"))
        self.BTN_Credentials_Clear.setStatusTip(_translate("MainWindow", "Deletes ALL saved usernames and passwords."))
        self.BTN_Credentials_Clear.setText(_translate("MainWindow", "Clear All Saved Data"))
        self.BTN_Credentials_Save.setStatusTip(_translate("MainWindow", "Update stored credentials"))
        self.BTN_Credentials_Save.setText(_translate("MainWindow", "Overwrite / Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_Credentials), _translate("MainWindow", "User Credentials"))
        self.LB_Feedback_header.setText(_translate("MainWindow", "Coming Soon"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_Feedback), _translate("MainWindow", "Feedback"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
#